Project.WebUI/Controllers/AnimalController.cs
using Project.BL.Repositories;
using Project.DAL.Entities;
using Project.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using X.PagedList;

namespace Project.WebUI.Controllers
{
    public class AnimalController : Controller
    {
        SqlRepo<Animal> repoAnimal;
        public AnimalController(SqlRepo<Animal> _repoAnimal)
        {
            repoAnimal = _repoAnimal;
        }
        public IActionResult Index(int? page)
        {
            AnimalVM animalVM = new AnimalVM
            {
                ListAnimal = repoAnimal.GetAll().Include(i => i.AnimalPictures).OrderByDescending(o => o.ID).Where(p => p.Enabled).ToPagedList(page ?? 1, 16),
            };
            return View(animalVM);
        }

        [Route("/animal/{name}-{id}")]
        public IActionResult Detail(string name, int id)
        {
            Animal animal = repoAnimal.GetAll().Include(i => i.AnimalPictures).FirstOrDefault(x => x.ID == id) ?? null;
            if (animal != null)
            {
                AnimalVM animalVM = new AnimalVM
                {
                    Animal = animal,
                    SimilarAnimals = repoAnimal.GetAll().Include(i => i.AnimalPictures).Take(4)

                };
                return View(animalVM);
            }
            else return Redirect("/");
        }
    }
}

Project.WebUI/Controllers/BlogController.cs
using Project.BL.Repositories;
using Project.DAL.Entities;
using Project.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using X.PagedList;

namespace Project.WebUI.Controllers
{
    public class BlogController : Controller
    {
        SqlRepo<Blog> repoBlog;
        SqlRepo<Comment> repoComment;
        public BlogController(SqlRepo<Blog> _repoBlog, SqlRepo<Comment> _repoComment)
        {
            repoBlog = _repoBlog;
            repoComment = _repoComment;
        }
        public IActionResult Index(int? page)
        {
            BlogVM blogVM = new BlogVM
            {
                ListBlog = repoBlog.GetAll().OrderByDescending(o => o.ID).ToPagedList(page ?? 1, 16),
            };
            return View(blogVM);

        }

        [Route("/blog/{name}-{id}")]
        public IActionResult Detail(BlogVM model, int id)
        {
            Blog blog = repoBlog.GetAll().Where(p => p.ID == id && p.Enabled).FirstOrDefault(x => x.ID == id) ?? null;
            ViewBag.deger = id;
            ViewBag.saat = DateTime.Now;

            if (model.Comment != null)
            {
                repoComment.Add(model.Comment);
                string[] mailto = new string[] { model.Comment.MailAddress };

            }
            else
            {
                if (blog != null)
                {
                    BlogVM blogVM = new BlogVM
                    {

                        PostComment = repoComment.GetAll().Where(p => p.BlogID == id).ToList(),
                        Blog = blog,
                    };
                    return View(blogVM);
                }
            }
            return RedirectToAction("Detail");
        }
    }
}

Project.WebUI/Controllers/ContactController.cs
using Project.BL.Repositories;
using Project.DAL.Entities;
using Project.WebUI.Tools;
using Project.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace Project.WebUI.Controllers
{
    public class ContactController : Controller
    {
        SqlRepo<Contact> repoContact;
        public ContactController( SqlRepo<Contact> _repoContact)
        {
            repoContact = _repoContact;
        }
        public IActionResult Index()
        {
            ContactVM contactVM = new ContactVM
            {
                Contact = new Contact(),
                
            };
            return View(contactVM);
        }

        [HttpPost]
        public IActionResult Index(ContactVM model)
        {
            if(ModelState.IsValid)
            {
                repoContact.Add(model.Contact);
                string[] mailto = new string[] { model.Contact.MailAddress };
                GeneralTool.SendMail("smtp.gmail.com", 587, "denemeinfotech@gmail.com", "deneme1234", true, "denemeinfotech@gmail.com", mailto, model.Contact.Subject,"Bu mail kişiden geldi:"+model.Contact.MailAddress+" mesajı ise:"+ model.Contact.Message);
            }
            else
            {
                ViewBag.Mesaj = "Veriler uygun gönderilmedi...";    
            }
            return RedirectToAction("Index");
        }
    }
}

Project.WebUI/Controllers/ProductController.cs
using Project.BL.Repositories;
using Project.DAL.Entities;
using Project.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using X.PagedList;

namespace Project.WebUI.Controllers
{
    public class ProductController : Controller
    {
        SqlRepo<Product> repoProduct;
        SqlRepo<Category> repoCategory;
        SqlRepo<Brand> repoBrand;
        public ProductController(SqlRepo<Product> _repoProduct, SqlRepo<Brand> _repoBrand, SqlRepo<Category> _repoCategory)
        {
            repoProduct = _repoProduct;
            repoCategory = _repoCategory;
            repoBrand = _repoBrand;
        }
        public IActionResult Index(int? page)
        {
            ProductVM productVM = new ProductVM
            {
                CategoryList = repoCategory.GetAll(),
                BrandList = repoBrand.GetAll(),
                ListProduct = repoProduct.GetAll().Include(i => i.ProductPictures).Where(p => p.Enabled).OrderByDescending(o => o.ID).ToPagedList(page ?? 1, 5),
            };
            return View(productVM);

        }

        [Route("/urun/{name}-{id}")]
        public IActionResult Detail(string name, int id)
        {
            Product product = repoProduct.GetAll().Include(i => i.ProductPictures).Where(p => p.Enabled).FirstOrDefault(x => x.ID == id) ?? null;
            if (product != null)
            {
                ProductVM productVM = new ProductVM
                {
                    Product = product,
                    SimilarProducts = repoProduct.GetAll().Include(i => i.ProductPictures).Where(w => w.BrandID == product.BrandID && w.ID != product.ID).Where(p => p.Enabled).Take(4)
                };
                return View(productVM);
            }
            else return Redirect("/");
        }
    }
}

Project.WebUI/Views/Shared/Components/Footer/Default.cshtml
@model FooterVM
<!-- Footer Section Begin -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="#"><img src="/img/logo/Plogo1.png" alt=""></a>
                    </div>
                    <p>Türkiye'nin online olarak hizmet veren en büyük petshop mağazası olma gururunu taşıyoruz! </p>
                    <a href="#"><img src="/img/payment.png" alt=""></a>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-2 col-sm-4">
                <div class="footer__widget">
                    <h6>Kategoriler</h6>
                    @foreach (Category c in Model.Categories)
                    {<ul><li><a href="">@c.Name</a></li></ul>}
                </div>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-4">
                <div class="footer__widget">
                    <h6>Bize Ulaşın</h6>
                    <ul>
                        <li><a asp-controller="Contact" asp-action="Index">İletişim</a></li>
                        <li><a href="#">Müşteri Hizmetleri</a></li>
                        <li><a href="#">Sipariş Takibi</a></li>
                        <li><a href="#">Sıkça Sorulan Sorular</a></li>
                        <li><a href="#">Gizlilik ve Güvenlik</a></li>
                        <li><a href="#">Garanti ve İade Koşulları</a></li>
                        <li><a asp-controller="Animal" asp-action="Index">Sahiplen</a></li>
                        <li><a asp-controller="Product" asp-action="Index">Ürünler</a></li>
                        <li><a asp-controller="Blog" asp-action="Index">Blog</a></li>

                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>BÜLTENİMİZE KAYIT OLUN</h6>
                    <div class="footer__newslatter">
                        <p></p>
                        <form action="#">
                            <input type="text" placeholder="Mail Adresiniz">
                            <button type="submit"><span class="icon_mail_alt"></span></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p>
                        <script>
                        </script>Bu site MuhammetErtem® Tarafından Gelişmiş E-Ticaret sistemleri ile hazırlanmıştır. <i></i><a></a>
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->
<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form asp-action="Search" method="get" class="search-model-form">
            <input type="search" name="keyword" id="search-input" placeholder="Arama">
        </form>
    </div>
</div>
<!-- Search End -->
<!-- Js Plugins -->
<script src="/js/jquery-3.3.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.nice-select.min.js"></script>
<script src="/js/jquery.nicescroll.min.js"></script>
<script src="/js/jquery.magnific-popup.min.js"></script>
<script src="/js/jquery.countdown.min.js"></script>
<script src="/js/jquery.slicknav.js"></script>
<script src="/js/mixitup.min.js"></script>
<script src="/js/owl.carousel.min.js"></script>
<script src="/js/main.js"></script>