Project.WebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Project.BL.Repositories;
using Project.DAL.Entities;
using Project.WebUI.Models;
using Project.WebUI.Tools;
using Project.WebUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Project.WebUI.Controllers
{
    public class CartController : Controller
    {
        SqlRepo<Product> repoProduct;
        SqlRepo<City> repoCity;
        SqlRepo<District> repoDistrict;
        public CartController(SqlRepo<Product> _repoProduct, SqlRepo<City> _repoCity, SqlRepo<District> _repoDistrict)
        {
            repoProduct = _repoProduct;
            repoCity = _repoCity;
            repoDistrict = _repoDistrict;
        }

        [Route("/sepetim")]
        public IActionResult Index()
        {
            if (Request.Cookies["SepetCookie"] != null)
            {
                List<Cart> carts = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["SepetCookie"]);
                return View(carts);
            }
            else return Redirect("/");
        }

        [Route("/sepet/ekle")]
        public string AddCart(int productID, int quantity, int stock)
        {
            string result = "";
            List<Cart> carts;
            Product product = repoProduct.GetAll().Include(i => i.ProductPictures).First(x => x.ID == productID) ?? null;
            string picture = product.ProductPictures.First().Path;
            if (string.IsNullOrEmpty(picture)) picture = "/img/noproduct.jpg";
            Cart cart = new Cart
            {
                ID = product.ID,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity,
                Picture = picture
            };
            if (Request.Cookies["SepetCookie"] == null)//sepet ile alakalı herhangi bir cookie yok yani ilk kez sepete ekleme işlemi
            {
                carts = new List<Cart>();
                carts.Add(cart);
            }
            else //daha önce sepete eklenen bir ürün var yani bir sepet cookie var
            {
                carts = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["SepetCookie"]);
                bool urunSepetteVarmi = false;
                foreach (Cart c in carts)
                {
                    if (c.ID == product.ID)//eğer ürün daha önce eklenen cookie de varsa miktarını artır
                    {
                        c.Quantity = quantity;
                        urunSepetteVarmi = true;
                    }
                }
                if (urunSepetteVarmi == false) carts.Add(cart);//eğer ürün daha önce eklenen cookie de yoksa cookideki listeye ekle
            }
            result = product.Name;
            CookieOptions cookieOptions = new CookieOptions();
            cookieOptions.Expires = DateTime.Now.AddDays(3);
            Response.Cookies.Append("SepetCookie", JsonConvert.SerializeObject(carts), cookieOptions);
            return result;

        }

        [Route("/sepet/urunsayisiver")]
        public int GetCartCount()
        {
            int result = 0;
            if (Request.Cookies["SepetCookie"] != null)
            {
                List<Cart> carts = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["SepetCookie"]);
                result = carts.Sum(c => c.Quantity);
            }
            return result;
        }
        [Route("/sepet/urunfiyativer")]
        public decimal GetCartPrice()
        {
            decimal result = 0;
            if (Request.Cookies["SepetCookie"] != null)
            {
                List<Cart> carts = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["SepetCookie"]);
                result = (decimal)carts.Sum(c => c.Price);
            }
            return result;
        }

        [Route("/sepetim/tamamla")]
        public IActionResult CheckOut()
        {
            if (Request.Cookies["SepetCookie"] != null)
            {
                List<Cart> carts = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["SepetCookie"]);
                CheckOutVM checkOutVM = new CheckOutVM { Carts = carts, Order = new Order(), Cities = repoCity.GetAll() };
                return View(checkOutVM);
            }
            else return Redirect("/");
        }

        [Route("/sepet/ilcegetir")]
        public List<District> getDistrict(int cityID)
        {
            return repoDistrict.GetAll(x => x.CityID == cityID).ToList();
        }
    }
}

Project.WebUI/Controllers/ContactController.cs
using Project.BL.Repositories;
using Project.DAL.Entities;
using Project.WebUI.Tools;
using Project.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace Project.WebUI.Controllers
{
    public class ContactController : Controller
    {
        SqlRepo<Contact> repoContact;
        public ContactController( SqlRepo<Contact> _repoContact)
        {
            repoContact = _repoContact;
        }
        public IActionResult Index()
        {
            ContactVM contactVM = new ContactVM
            {
                Contact = new Contact(),
                
            };
            return View(contactVM);
        }

        [HttpPost]
        public IActionResult Index(ContactVM model)
        {
            if(ModelState.IsValid)
            {
                repoContact.Add(model.Contact);
                string[] mailto = new string[] { model.Contact.MailAddress };
                GeneralTool.SendMail("smtp.gmail.com", 587, "denemeinfotech@gmail.com", "deneme1234", true, "denemeinfotech@gmail.com", mailto, model.Contact.Subject,"Bu mail kişiden geldi:"+model.Contact.MailAddress+" mesajı ise:"+ model.Contact.Message);
            }
            else
            {
                ViewBag.Mesaj = "Veriler uygun gönderilmedi...";    
            }
            return RedirectToAction("Index");
        }
    }
}

Project.WebUI/Views/Shared/Components/Header/Default.cshtml
@model HeaderVM
@{

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="header__logo">
                        <a href="/"><img src="/img/logo/Plogo3.png" alt=""></a>
                    </div>
                </div>
                <div class="col-md-auto">
                    <nav class="header__menu mobile-menu">
                        @*<ul>

                    <li>
                        <a href="#">Pages</a>
                        <ul class="dropdown">
                            <li><a href="./about.html">About Us</a></li>
                            <li><a href="./shop-details.html">Shop Details</a></li>
                            <li><a href="./shopping-cart.html">Shopping Cart</a></li>
                            <li><a asp-controller="Contact" asp-action="Index">Check Out</a></li>
                            <li><a href="./blog-details.html">Blog Details</a></li>
                        </ul>
                    </li>

                </ul>*@
                        <ul>
                            @foreach (Category c in Model.Categories)
                            {
                                <li>
                                    <a href="#">
                                        @c.Name
                                    </a>

                                    <div class="dropdown">
                                        @foreach (var s in c.SubCategories)
                                        {
                                            <a class="dropdown-item" style="font-size: 14px; background-color: #212529; color: #fff; font-weight: 400; padding: 5px 20px; text-transform: capitalize; text-decoration: none; background-color: transparent; white-space: pre-wrap; " asp-route="SubCategory" asp-route-name="@GeneralTool.ConvertURL(s.Name)" asp-route-id="@s.ID">@s.Name</a>
                                        }
                                    </div>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
                <div class="col">
                    <div class="header__nav__option">
                        <a href="#" class="search-switch"><img src="/img/icon/search.png" alt=""></a>
                        <a class="kullanici"><img src="/img/icon/user1.png" alt=""></a>
                        <a asp-controller="Cart" asp-action="Index"><img src="/img/icon/cart.png" alt=""> <span>0</span></a>
                        <div class="price">0.00 ₺</div>
                    </div>

                </div>
            </div>
            <div class="canvas__open"><i class="fa fa-bars"></i></div>
        </div>
    </header>
    <!-- Header Section End -->


}